---
# tasks file for sap-hana-preconfigure configuration

- debug:
    msg: "sapnote/assert-2777782.yml"

# The following task is already part of role sap-preconfigure:
- import_tasks: 2777782/01-assert-selinux.yml
  when: sap_hana_preconfigure_assert_config_all|d(true) or sap_hana_preconfigure_assert_2777782_01|d(false)

- import_tasks: 2777782/02-assert-tuned.yml
  when: sap_hana_preconfigure_assert_config_all|d(true) or sap_hana_preconfigure_assert_2777782_02|d(false)

- import_tasks: 2777782/03-assert-abrt-coredumps-kdump.yml
  when: sap_hana_preconfigure_assert_config_all|d(true) or sap_hana_preconfigure_assert_2777782_03|d(false)

- import_tasks: 2777782/04-assert-auto-numa-balancing.yml
  when: sap_hana_preconfigure_assert_config_all|d(true) or sap_hana_preconfigure_assert_2777782_04|d(false)

- import_tasks: 2777782/05-assert-thp.yml
  when: sap_hana_preconfigure_assert_config_all|d(true) or sap_hana_preconfigure_assert_2777782_05|d(false)

- import_tasks: 2777782/06-assert-c-states-for-lower-latency.yml
  when: sap_hana_preconfigure_assert_config_all|d(true) or sap_hana_preconfigure_assert_2777782_06|d(false)

- import_tasks: 2777782/07-assert-cpu-governor.yml
  when: sap_hana_preconfigure_assert_config_all|d(true) or sap_hana_preconfigure_assert_2777782_07|d(false)

- import_tasks: 2777782/08-assert-epb.yml
  when: sap_hana_preconfigure_assert_config_all|d(true) or sap_hana_preconfigure_assert_2777782_08|d(false)

- import_tasks: 2777782/09-assert-ksm.yml
  when: sap_hana_preconfigure_assert_config_all|d(true) or sap_hana_preconfigure_assert_2777782_09|d(false)

- import_tasks: 2777782/10-assert-pidmax.yml
  when: sap_hana_preconfigure_assert_config_all|d(true) or sap_hana_preconfigure_assert_2777782_10|d(false)

