---
# OS RELEASE: RHEL  7.x
# Check EUS Channels
# https://launchpad.support.sap.com/#/notes/2009879
# 
# This SAP Note Contains the general installation guides for all RHEL 7.x systems in PDF format
#
# Some of these tasks are documented already in SAP NOTE 2292690
# See comments
#

### 3.1 - Basic OS installation is a prerequisite
### 3.2 - Additional Package installation is done in the installation.yml file
### 3.3 - Hostname - is an SAP generic setting, already done with SAP Note 2002167 (sap-preconfigure) 
### 3.4 - NTP/Chrony - is a generic SAP requirement, needs to be done by linux-system-roles.timesync
### 3.5 - Configure Storage - out of scooe, have a look at linux-system-roles.storage
### 3.6 - Activate SAP HANA specific tuned profile -> SAP Note 2292690
### 3.7 - Disable SE Linux -> SAP Note 2292690, SAP NOTE 2002167
### 3.8 - Disable Numa Balancing -> SAP Note 2292690 

### 3.9 - Create the compatibility links for HANA 
- block:
  - name: 3.9 create compatibility links for RHEL 7.2
    file: src=/usr/lib64/{{ line_item.src }} dest=/usr/lib64/{{ line_item.dest }} state=link
    with_items:
      - { src: 'libssl.so.1.0.1e', dest: 'libssl.so.1.0.1' }
      - { src: 'libcrypto.so.1.0.1e', dest: 'libcrypto.so.1.0.1' }
    when: 
       ( ansible_distribution_version  == '7.2' )
    loop_control:
      loop_var: line_item

  - name: 3.9 create compatibility links for RHEL 7.3+
    file: src=/usr/lib64/{{ line_item.src }} dest=/usr/lib64/{{ line_item.dest }} state=link
    with_items:
      - { src: 'libssl.so.10', dest: 'libssl.so.1.0.1' }
      - { src: 'libcrypto.so.10', dest: 'libcrypto.so.1.0.1' }
    when: 
       ( ansible_distribution_version  != '7.2' )
    loop_control:
      loop_var: line_item

  when: sap_hana_preconfigure_assert_config_all|d(true) or sap_hana_preconfigure_assert_2009879_3_9|d(false)

### 3.10 - THP -> SAP Note 2292690 
### 3.11 - CPU Governor for performance -> TunedProfile -> SAP Note 2292690
### 3.12 - Processor C-States für x86_64 -> SAP Note 2292690

### Set by HANA installer
#- name: increase file handles to 32800 for sapsys group
#  pam_limits: 
#    dest: /etc/security/limits.d/99-sapsys.conf
#    domain: "@sapsys" 
#    limit_item: nofile 
#    limit_type: "{{ line_item }}" 
#    value: 32800
#  with_items:
#    - soft
#    - hard
#  loop_control:
#    loop_var: line_item

### 3.13 - set number of process to unlimited for sapsys group
- name: 3.13 Set the hard and soft limit for the max number of processes per user (nproc) to unlimited for group sapsys
  pam_limits:
    dest: /etc/security/limits.d/99-sap.conf
    domain: "@sapsys"
    limit_item: nproc
    limit_type: "{{ line_item }}"
    value: unlimited
  with_items:
    - hard
    - soft
  loop_control:
    loop_var: line_item
  when: sap_hana_preconfigure_assert_config_all|d(true) or sap_hana_preconfigure_assert_2009879_3_13|d(false)

### 3.14 - Disable ABRT
- include_tasks: ../RedHat/generic/disable-abrt.yml
  when: sap_hana_preconfigure_assert_config_all|d(true) or sap_hana_preconfigure_assert_2009879_3_14_1|d(false)

- include_tasks: ../RedHat/generic/disable-abrt-ccpp.yml
  when: sap_hana_preconfigure_assert_config_all|d(true) or sap_hana_preconfigure_assert_2009879_3_14_2|d(false)

### 3.14 - Disable core Dumps
- include_tasks: ../RedHat/generic/disable-coredumps.yml
  when: sap_hana_preconfigure_assert_config_all|d(true) or sap_hana_preconfigure_assert_2009879_3_14_3|d(false)

### 3.14 - Disable Kdump
- include_tasks: ../RedHat/generic/disable-kdump.yml
  when: sap_hana_preconfigure_assert_config_all|d(true) or sap_hana_preconfigure_assert_2009879_3_14_4|d(false)

### 3.15 - Disable Firewalld
### Firewall Settings can only be done if SAP instance ID is known,
### otherwise disable firewall
### NYI: Set proper firewall rules if SID/instance number is known
###
- include_tasks: ../RedHat/generic/disable-firewall.yml
# - name: 3.15 Ensure firewall is disabled when instance ID unknown
#   service: name=firewalld state=stopped enabled=no
#   ignore_errors: True


### Firewall Calculation for SID=xx
##################################################################
# Schema                     | Description
# ---------------------------+------------------------------------
# 3xx09                      | Administration port for SAP HANA
# 1128 - 1129, 5xx13 - 5xx14 | SAP HANA Studio
# 43xx, 80xx                 | Company Network
# 3xx15, 3xx17               | SAP HANA Studio + Replication
#
# NYI: Create this service in case SID is defined
#
# example file for SID=99, but what to replace for destination ??
# Maybe this could be moved to hana-deploy !
#
# <?xml version="1.0" encoding="utf-8"?>
# <service>
# <short>SAP HANA</short>
# <description>Firewall rules for SAP HANA</description>
# <port port="39909" protocol="tcp"/>
# <port port="1128" protocol="tcp"/>
# <port port="1129" protocol="tcp"/>
# <port port="4399" protocol="tcp"/>
# <port port="8099" protocol="tcp"/>
# <port port="59913" protocol="tcp"/>
# <port port="59914" protocol="tcp"/>
# <port port="39915" protocol="tcp"/>
# <port port="39917" protocol="tcp"/>
# <port port="39901" protocol="tcp"/>
# <port port="39907" protocol="tcp"/>
# <destination ipv4="192.168.0.33"/>
# </service>
#
