---
# OS RELEASE: RHEL 7
# Platform: PPC64LE
# SAP Note: 2055470
# https://launchpad.support.sap.com/#/notes/2055470
# The SAP Note points to http://www-03.ibm.com/support/techdocs/atsmastr.nsf/WebIndex/WP102502

## On the above page you will find more PDF documents, the following is used in this config file:
## Configuring your Network for SAP HANA (Ethernet connectivity): 
## http://www-03.ibm.com/support/techdocs/atsmastr.nsf/5cb5ed706d254a8186256c71006d2e0a/c32b40501f4f76c886257de0004fa1d4/$FILE/Network_Configuration_for_HANA_Workloads_on_IBM_Power_Servers_V4.pdf

- name: ensure MTU size is 9000 on all interfaces
  shell: |
    mtu=$(nmcli conn show {{ line_item }} | grep 802-3-ethernet.mtu | awk -F: '{printf("%d", $2)}')
    if [ "$mtu" != "9000" ]; then
       nmcli conn mod {{ line_item }} 802-3-ethernet.mtu "9000"
       ip link set mtu 9000 dev {{ line_item }}
    else
       exit 90
    fi
  register: sapnote_2055470_mtusize
  changed_when: sapnote_2055470_mtusize.rc == 0
  failed_when: sapnote_2055470_mtusize.rc > 0 and sapnote_2055470_mtusize.rc != 90
  with_items: "{{ sap_hana_preconfigure_assert_ppcle_mtu9000_if }}"
  when: not( (sap_hana_preconfigure_assert_ppcle_mtu9000_if) or ( sap_hana_preconfigure_assert_ppcle_mtu9000_if is none) or (sap_hana_preconfigure_assert_ppcle_mtu9000_if | trim == '') )
  loop_control:
    loop_var: line_item

## This only works if interfacename=device name, otherwise it fails 
- name: add largesend options to interface
  lineinfile:
    regexp: '^ETHTOOL_OPTIONS_tso='
    line: ETHTOOL_OPTIONS_tso='-K iface tso on'
    path: /etc/sysconfig/network-scripts/ifcfg-{{ line_item }}
  with_items: "{{ sap_hana_preconfigure_assert_ppcle_tso_if }}"
  when: not( (sap_hana_preconfigure_assert_ppcle_tso_if) or ( sap_hana_preconfigure_assert_ppcle_tso_if is none) or (sap_hana_preconfigure_assert_ppcle_tso_if | trim == '') )
  loop_control:
    loop_var: line_item
  
- name: add largesend parameter
  sysctl:
    sysctl_file: /etc/sysctl.d/ibm_largesend.conf
    name: "{{ line_item.name }}"
    value: "{{ line_item.value }}"
    state: present
    sysctl_set: yes
    reload: yes
  with_items:
    - { name: net.core.rmem_max, value: 56623104 }
    - { name: net.core.wmem_max, value: 56623104 }
    - { name: net.ipv4.tcp_rmem, value: "65536 262088 56623104" }
    - { name: net.ipv4.tcp_wmem, value: "65536 262088 56623104" }
    - { name: net.ipv4.tcp_mem, value: "56623104 56623104 56623104" }
  loop_control:
    loop_var: line_item

...
