---
# tasks file for sap-hana-preconfigure: configuration

- debug:
    msg: "SAP note 2772999: RHEL 8 configuration for SAP"

- debug:
    msg: "sapnote/assert-2772999.yml"

- block:
    - debug:
        msg: "SAP note 2772999 Step 9: Configure Process Resource Limits"

    - name: Get info about file /etc/security/limits.d/99-sap.conf
      stat:
        path: /etc/security/limits.d/99-sap.conf
      register: stat_sap_conf_2

    - name: Assert that file /etc/security/limits.d/99-sap.conf exists
      assert:
        that: "stat_sap_conf_2.stat.isreg == true"
        fail_msg: "FAIL: The file /etc/security/limits.d/99-sap.conf does not exist or is no regular file!"
        success_msg: "PASS: The file /etc/security/limits.d/99-sap.conf exists and is a regular file."
      ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"

    - name: Get the hard limit of nproc for group sapsys
      command: awk '/sapsys/&&/nproc/&&/hard/{print $NF}' /etc/security/limits.d/99-sap.conf
      register: awk_nofile_hard_result
      changed_when: no
      ignore_errors: yes

    - name: Assert that the hard limit of nproc is unlimited for group sapsys
      assert:
        that:
          - awk_nofile_hard_result.stdout == 'unlimited'
        fail_msg: "FAIL: The hard limit of nproc is not set to 'unlimited' in /etc/security/limits.d/99-sap.conf!"
        success_msg: "PASS: The hard limit of nproc is set to 'unlimited' in /etc/security/limits.d/99-sap.conf."
      ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"

    - name: Get the soft limit of nproc for group sapsys
      command: awk '/sapsys/&&/nproc/&&/soft/{print $NF}' /etc/security/limits.d/99-sap.conf
      register: awk_nofile_soft_result
      changed_when: no
      ignore_errors: yes

    - name: Assert that the soft limit of nproc is unlimited for group sapsys
      assert:
        that:
          - awk_nofile_soft_result.stdout == 'unlimited'
        fail_msg: "FAIL: The soft limit of nproc is not set to 'unlimited' in /etc/security/limits.d/99-sap.conf!"
        success_msg: "PASS: The soft limit of nproc is set to 'unlimited' in /etc/security/limits.d/99-sap.conf."
      ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"

    - debug:
        msg: "WARN: Check of the hard and soft limit of nproc for the database group not implemented. Please check manually!"

#  - name: Set the hard and soft limit for the max number of open files per process (nproc) to unlimited for the database group
#    pam_limits:
#      dest: /etc/security/limits.d/99-sap.conf
#      domain: "{{ sap_hana_preconfigure_assert_db_group_name }} "
#      limit_item: nproc
#      limit_type: "{{ line_item }}"
#      value: unlimited
#    with_items:
#      - hard
#      - soft
#    loop_control:
#      loop_var: line_item
#    when:
#      - sap_hana_preconfigure_assert_db_group_name is defined

  when: sap_hana_preconfigure_assert_config_all|d(true) or sap_hana_preconfigure_assert_2772999_09|d(false)

...
