---

- debug:
    msg: "imported RedHat/generic/assert-kdump.yml"

- name: Get status of kdump
  command: systemctl status kdump
  register: kdump_status
  ignore_errors: yes
  changed_when: no

- name: Assert that kdump is disabled
  assert:
    that:
      - "'/usr/lib/systemd/system/kdump.service; disabled' in kdump_status.stdout"
    fail_msg: "FAIL: Service 'kdump' is not disabled!"
    success_msg: "PASS: Service 'kdump' is disabled."
  ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"

- name: Assert that kdump is inactive
  assert:
    that:
      - "'inactive (dead)' in kdump_status.stdout"
    fail_msg: "FAIL: Service 'kdump' is active!"
    success_msg: "PASS: Service 'kdump' is inactive."
  ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"

...
