---

- debug:
    msg: "imported RedHat/generic/assert-c-states-for-lower-latency.yml"

# can be configured by tuned profile sap-hana, entry "force_latency=70"
- block:
    - name: Get contents of GRUB_CMDLINE_LINUX in /etc/default/grub
      command: grep GRUB_CMDLINE_LINUX /etc/default/grub
      register: grep_default_grub_result
      changed_when: no

    - name: Assert that processor.max_cstate=1 is in GRUB_CMDLINE_LINUX in /etc/default/grub
      assert:
        that:
          - "'processor.max_cstate=1' in grep_default_grub_result.stdout"
        fail_msg: "FAIL: 'processor.max_cstate=1' is not in GRUB_CMDLINE_LINUX in /etc/default/grub!"
        success_msg: "PASS: 'processor.max_cstate=1' is in GRUB_CMDLINE_LINUX in /etc/default/grub."
      ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"

    - name: Assert that intel_idle.max_cstate=1 is in GRUB_CMDLINE_LINUX in /etc/default/grub
      assert:
        that:
          - "'intel_idle.max_cstate=1' in grep_default_grub_result.stdout"
        fail_msg: "FAIL: 'intel_idle.max_cstate=1' is not in GRUB_CMDLINE_LINUX in /etc/default/grub!"
        success_msg: "PASS: 'intel_idle.max_cstate=1' is in GRUB_CMDLINE_LINUX in /etc/default/grub."
      ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"

  when:
    - ansible_os_family == 'RedHat'
    - sap_hana_preconfigure_assert_modify_grub_cmdline_linux
    - not sap_hana_preconfigure_assert_use_tuned_where_possible

...
