---

- debug:
    msg: "imported RedHat/generic/disable-ksm.yml"

- name: Create file /etc/init.d/boot.local if it does not exist
  file:
    path: /etc/init.d/boot.local
    state: touch
    mode: 0755

- name: Disable KSM at boot time
  lineinfile:
    dest: /etc/init.d/boot.local
    line: "echo 0 > /sys/kernel/mm/ksm/run"

- name: Disable KSM on the running system
  command: bash -lc "echo 0 > /sys/kernel/mm/ksm/run"
  register: command_result
- debug:
    var: command_result.stdout_lines, command_result.stderr_lines

- name: Get status of KSM
  command: bash -lc "cat /sys/kernel/mm/ksm/run"
  register: command_result
  ignore_errors: true
  changed_when: false
- debug:
    var: command_result.stdout_lines, command_result.stderr_lines

...
