---

#- name: Enable Debugging
#  debug:
#    verbosity: "{{ debuglevel }}"
#
- name: list of required SAP Notes
  debug: 
    var: __sap_hana_preconfigure_assert_sapnotes | difference([''])

- name: Gather service facts
  service_facts:

- name: include configuration actions for required sapnotes 
  include_tasks: "sapnote/assert-{{ item }}.yml"
  with_items: "{{ __sap_hana_preconfigure_assert_sapnotes | difference(['']) }}"
     
- include: "{{ './' + ansible_distribution + '_' + ansible_distribution_major_version + '/recommendations.yml' }}"

- include: "{{ './' + ansible_distribution + '_' + ansible_distribution_major_version + '/parameter-checks.yml' }}"

...
