---

- debug:
    msg: "SAP note 2777782 Step 3: Disable ABRT, core dumps, and kdump"
- import_tasks: ../../RedHat/generic/assert-abrtd.yml
- import_tasks: ../../RedHat/generic/assert-abrt-ccpp.yml
- import_tasks: ../../RedHat/generic/assert-coredumps.yml
- import_tasks: ../../RedHat/generic/assert-kdump.yml

...
