---

- debug:
    msg: "SAP note 2292690 Step 9: Database startup fails with an error message - /etc/sudoers"
- name: Ensure "Defaults requiretty" is not set in /etc/sudoers
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults[ \s]*requiretty'
    validate: '/usr/sbin/visudo -cf %s'

...
