---

#### Special recommendations for Power 8
- debug:
    msg: "SAP note 2292690 Step 10: IBM EnergyScale for POWER8 Processor-Based Systems"

- name: Check of package pseries-energy
  block:
    - name: Check if package pseries-energy is not installed
      shell: yum info installed pseries-energy
      register: yum_pseries_energy_result
      changed_when: no
      args:
        warn: false

    - name: Assert that package pseries-energy is not installed
      assert:
        that:
          - yum_pseries_energy_result.rc == 1
        fail_msg: "FAIL: Package 'pseries-energy' is installed!"
        success_msg: "PASS: Package 'pseries-energy' is not installed."

  when: ansible_architecture == "ppc64le"

...
