---

#### Special recommendations for Power 8
- debug:
    msg: "SAP note 2292690 Step 10: IBM EnergyScale for POWER8 Processor-Based Systems"
- name: ensure pseries-energy package is not installed
  yum:
    name: pseries-energy
    state: absent
  when: ansible_architecture == "ppc64le"

...
